# Playing with matrices
(and if you get the subliminal message about abstractions, we'll be thrilled!)

Julia is a dynamic language.  You don't need type declarations, and can change variable types dynamically and interactively.

For working with simple numbers, arrays, and strings, its syntax is *superficially* similar to Matlab, Python, and other popular languages.

In order to execute the `In` cells, select the cell and press `Shift-Enter`, or press the `Play` button above. To run the entire notebook, navigate to the `Cell` menu and then `Run All`.

# We tell beginners, you don't need types!

In [2]:
typeof(1.0)

Float64

In [3]:
typeof(1)

Int64

In [7]:
bits(1.0)

"0011111111110000000000000000000000000000000000000000000000000000"

In [8]:
S = "Hello Julia Clsas"
typeof(S)

String

In [9]:
#  Exercise fix my spelling in the cell above
S

"Hello Julia Clsas"

# Now forget all that (for now): Julia is not so different from your favorite dynamic language

In [19]:
a = 'a'
1 + a

# shift + enter to run

'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)

In [24]:
A = rand(['a','b'],5,5)

5×5 Array{Char,2}:
 'b'  'a'  'a'  'a'  'b'
 'a'  'a'  'a'  'a'  'a'
 'a'  'a'  'a'  'b'  'b'
 'b'  'b'  'b'  'b'  'a'
 'b'  'b'  'b'  'a'  'b'

In [27]:
A = SymTridiagonal(rand(1:4,4), rand(1:3,3))

4×4 SymTridiagonal{Int64}:
 3  2  ⋅  ⋅
 2  4  3  ⋅
 ⋅  3  3  2
 ⋅  ⋅  2  1

In [35]:
A .* 7

4×4 SparseMatrixCSC{Int64,Int64} with 10 stored entries:
  [1, 1]  =  21
  [2, 1]  =  14
  [1, 2]  =  14
  [2, 2]  =  28
  [3, 2]  =  21
  [2, 3]  =  21
  [3, 3]  =  21
  [4, 3]  =  14
  [3, 4]  =  14
  [4, 4]  =  7

In [28]:
dump(A)

SymTridiagonal{Int64}
  dv: Array{Int64}((4,)) [3, 4, 3, 1]
  ev: Array{Int64}((3,)) [2, 3, 2]


In [31]:
b = rand(4)
A \ b # Solve Ax = b for x

4-element Array{Float64,1}:
  0.551501
 -0.392238
  0.266373
  0.411816

In [38]:
A = fill(2, 4, 5) # Fill a 5x5 array with 3.15's

4×5 Array{Int64,2}:
 2  2  2  2  2
 2  2  2  2  2
 2  2  2  2  2
 2  2  2  2  2

# Let's create some addition tables

First let's use a nested for loop to fill in a matrix that's initially zero:

In [42]:
A = zeros(Int, 5, 5)

for i in 1:5
    for j in 1:5
        A[i, j] = i+j  # Square brackets for indices.  Also: indices start at 1, not 0.
    end
end

A

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

We can abbreviate this using a double `for` loop:

In [43]:
for i in 1:5, j in 1:5
   A[i, j] = i+j  # Square brackets for indices.  Also: indices start at 1, not 0.
end

A

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

The Julia way would be to use a so-called **array comprehension**:

In [44]:
[i+j for i in 1:5, j in 1:5]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [45]:
# Equivalently,
[i+j for i = 1:5, j = 1:5]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [46]:
[i+j for i ∈ 1:5, j ∈ 1:5] # \in + <tab> yields ∈

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [54]:

♡ = 3
♡ ^ 10
"I ♡ San Sebastian"

"I ♡ San Sebastian"

**Explore**: What does the following do? 

In [57]:
[i for i in sin.(1:7)]

7-element Array{Float64,1}:
  0.841471
  0.909297
  0.14112 
 -0.756802
 -0.958924
 -0.279415
  0.656987

In [56]:
# What happens when  we remove the dot syntax?
[i for i in (1:7)^2]

LoadError: DimensionMismatch("Cannot multiply two vectors")

In [ ]:
[i^2 for i in 1:7]

**Explore**: What does the following do? 

In [ ]:
sort(unique(x^2 + y^2 for x in 1:5, y in 1:5))  # The inner parentheses define a **generator**

Suppose we want to see $n \times n$ multiplication tables for $n=1,2,3,4,5$:

In [58]:
for n in 1:5
    display([i*j for i=1:n, j=1:n])
end

1×1 Array{Int64,2}:
 1

2×2 Array{Int64,2}:
 1  2
 2  4

3×3 Array{Int64,2}:
 1  2  3
 2  4  6
 3  6  9

4×4 Array{Int64,2}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

5×5 Array{Int64,2}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

# `Interact.jl` is a Julia *package* for interacting with data

It's way more fun to **interact** with our data.
We install the `Interact.jl` package as follows; this needs to be executed only once for any given Julia installation:

In [ ]:
# Pkg.add("Interact")

Now we load the package with the following `using` command, in each Julia session:

In [59]:
using Interact

The package contains a `@manipulate` macro, that is wrapped around a `for` loop:

In [60]:
@manipulate for n in 1:1000
    n
end

Interact.Options{:SelectionSlider,Any}(1: "input" = 500 Any , "n", 500, "500", 500, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…), Dict{Any,Any}(Pair{Any,Any}(306, "306"),Pair{Any,Any}(29, "29"),Pair{Any,Any}(74, "74"),Pair{Any,Any}(905, "905"),Pair{Any,Any}(176, "176"),Pair{Any,Any}(892, "892"),Pair{Any,Any}(285, "285"),Pair{Any,Any}(318, "318"),Pair{Any,Any}(873, "873"),Pair{Any,Any}(975, "975")…)), Any[], Any[], true, "horizontal")

500

In [61]:
@manipulate for n in 1:20
    [i*j for i in 1:n, j in 1:n]
end

Interact.Options{:SelectionSlider,Any}(5: "input-2" = 10 Any , "n", 10, "10", 10, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…), Dict{Any,Any}(Pair{Any,Any}(18, "18"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(16, "16"),Pair{Any,Any}(11, "11"),Pair{Any,Any}(7, "7"),Pair{Any,Any}(9, "9"),Pair{Any,Any}(10, "10"),Pair{Any,Any}(19, "19"),Pair{Any,Any}(17, "17"),Pair{Any,Any}(8, "8")…)), Any[], Any[], true, "horizontal")

10×10 Array{Int64,2}:
  1   2   3   4   5   6   7   8   9   10
  2   4   6   8  10  12  14  16  18   20
  3   6   9  12  15  18  21  24  27   30
  4   8  12  16  20  24  28  32  36   40
  5  10  15  20  25  30  35  40  45   50
  6  12  18  24  30  36  42  48  54   60
  7  14  21  28  35  42  49  56  63   70
  8  16  24  32  40  48  56  64  72   80
  9  18  27  36  45  54  63  72  81   90
 10  20  30  40  50  60  70  80  90  100

We use a double `for` loop to get a double slider!

In [62]:
@manipulate for n in 3:10, i in 1:9
   A = fill(0, n, n)
   A[1:3, 1:3] = i    # fill a sub-block
A
end

Interact.Options{:SelectionSlider,Any}(9: "input-3" = 6 Any , "n", 6, "6", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(9, "9"),Pair{Any,Any}(10, "10"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"))), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(11: "input-4" = 5 Any , "i", 5, "5", 5, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(9, "9"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

6×6 Array{Int64,2}:
 5  5  5  0  0  0
 5  5  5  0  0  0
 5  5  5  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

# Functions

Julia is built around functions: all "commands" or "operations" in Julia are functions:

In [63]:
# verbose form:
function f(x)
    x^2
end

# one-line form:
f2(x) = x^2

# anonymous form:
f3 =  x -> x^2;

In [64]:
f(10)

100

Functions just work, as long as they make sense:

In [65]:
# The square of a matrix is unambiguously defined
f(rand(3, 3))

3×3 Array{Float64,2}:
 0.611222  0.864742  0.799587
 0.290661  0.374159  0.342991
 0.546469  1.02709   0.817094

In [66]:
# What the 'square of a vector' means is ambiguous
f(rand(3))

LoadError: DimensionMismatch("Cannot multiply two vectors")

In [67]:
# In the definition below, `a` and `power` are optional arguments to `f`, supplied with default values.
function f(x, a=1, power=2)
    a*x^power
end

f (generic function with 3 methods)

In [68]:
# `a` defaults to 1 and `power` to 2
f(7)

49

In [69]:
# The first optional argument passed is assigned to the local variable `a`
# `power` defaults to 2
f(10, 3)

300

In [70]:
f(10, 3, 3)

3000

Let's define a function to insert a block in a matrix:

In [71]:
function insert_block(A, i, j, what=7)
    B = A[:,:]        # B is a copy of A       
    B[i:i+2, j:j+2] = fill(what, 3, 3)
    
    return B          # the `return` keyword is optional
end

insert_block (generic function with 2 methods)

In [72]:
A = fill(0, 9, 9)
insert_block(A, 3, 5)  # this returns the new matrix

9×9 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  7  7  7  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0

In [73]:
A = fill(0, 9, 9)
insert_block(A, 3, 5, 2)  # Use 2 instead of 7

9×9 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  2  2  2  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0

We can move the block around:

In [74]:
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j)
end

Interact.Options{:SelectionSlider,Any}(15: "input-5" = 4 Any , "i", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(17: "input-6" = 4 Any , "j", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

# Strings

Julia can manipulate strings easily:

In [80]:
S = "Hello"
println(S)
T = 47

Hello


47

In [82]:
a = "I am a string"
typeof(a)

String

In [87]:
b = '♡'
typeof(b)
c = [ b, b, b]
String(c)

"♡♡♡"

In [88]:
replace(S, "H", "J")

"Jello"

In [89]:
a = 3

3

In [90]:
string(S, " ", S, " ", "Julia; a = ", a)  # build a string by concatenating things

"Hello Hello Julia; a = 3"

In [98]:
c = '4'
string( "abc", ' ',"123"," ", "$c")

"abc 123 4"

More about strings: <a href="http://docs.julialang.org/en/stable/manual/strings/"> Julia Doc on Strings </a>

Functions in Julia try to be **generic**, i.e. to work with as many kinds of object as possible:

In [99]:
A = fill("Julia", 5, 5)

5×5 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"  "Julia"

Julia allows us to display objects in different ways. For example, the following code displays a matrix of strings
in the notebook using an HTML representation:

In [100]:
function Base.show{T<:String}(io::IO, ::MIME"text/html", M::Matrix{T}) 
    max_length = maximum(length.(M))
    dv="<div style='display:flex;flex-direction:row'>"
    print(io, dv*join([join("<div style='width:40px; text-align:center'>".*M[i,:].*"</div>", " ") for i in 1:size(M, 1)]
            , "</div>$dv")*"</div>")
end

In [ ]:
A

In [101]:
# Remember this ????
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j)
end

Interact.Options{:SelectionSlider,Any}(21: "input-7" = 4 Any , "i", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(23: "input-8" = 4 Any , "j", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

Let's use the **same code**, but now with strings:

In [102]:
A = fill("Julia", 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j, "[FUN]")
end

Interact.Options{:SelectionSlider,Any}(27: "input-9" = 4 Any , "i", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(29: "input-10" = 4 Any , "j", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "[FUN]"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "[FUN]"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "[FUN]"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"

In [103]:
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, "π")
end

Interact.Options{:SelectionSlider,Any}(33: "input-11" = 4 Any , "i", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(35: "input-12" = 4 Any , "j", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "π"      …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"

In [104]:
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, "♡")
end

Interact.Options{:SelectionSlider,Any}(39: "input-13" = 4 Any , "i", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(41: "input-14" = 4 Any , "j", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

10×10 Array{String,2}:
 "Julia"  "Julia"  "Julia"  "Julia"  …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"         "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "♡"      …  "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"  "Julia"     "Julia"  "Julia"  "Julia"  "Julia"

In [105]:
airplane = "✈"
alien = "👽"
rand([airplane, alien], 5, 5)

5×5 Array{String,2}:
 "👽"  "✈"  "👽"  "👽"  "✈"
 "✈"  "👽"  "✈"  "👽"  "👽"
 "✈"  "✈"  "✈"  "👽"  "✈"
 "✈"  "👽"  "👽"  "👽"  "✈"
 "✈"  "👽"  "✈"  "✈"  "✈"

In [106]:
A = fill(airplane, 9, 9)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, alien)
end

Interact.Options{:SelectionSlider,Any}(45: "input-15" = 4 Any , "i", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(47: "input-16" = 4 Any , "j", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

9×9 Array{String,2}:
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "👽"  "👽"  "👽"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"
 "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"  "✈"

# Colors

The `Colors` package provides objects representing colours:

In [107]:
#Pkg.add("Colors")
using Colors

# import Colors as c

In [114]:
distinguishable_colors(12)

In [109]:
@manipulate for n in 1:80
    Cdistinguishable_colors(n)
end

Interact.Options{:SelectionSlider,Any}(51: "input-17" = 40 Any , "n", 40, "40", 40, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10…), Dict{Any,Any}(Pair{Any,Any}(68, "68"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(11, "11"),Pair{Any,Any}(39, "39"),Pair{Any,Any}(46, "46"),Pair{Any,Any}(25, "25"),Pair{Any,Any}(55, "55"),Pair{Any,Any}(42, "42"),Pair{Any,Any}(29, "29"),Pair{Any,Any}(58, "58")…)), Any[], Any[], true, "horizontal")

In [111]:
colors = distinguishable_colors(100)
typeof(colors)

Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},1}

In [112]:
# Remember this ????
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j)
end

Interact.Options{:SelectionSlider,Any}(55: "input-18" = 4 Any , "i", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(57: "input-19" = 4 Any , "j", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

10×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  7  7  7  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

What happens if we use colors instead?

In [113]:
A = fill(colors[1], 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, colors[4])
end

Interact.Options{:SelectionSlider,Any}(61: "input-20" = 4 Any , "i", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(63: "input-21" = 4 Any , "j", 4, "4", 4, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("1"=>1,"2"=>2,"3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8), Dict{Any,Any}(Pair{Any,Any}(7, "7"),Pair{Any,Any}(4, "4"),Pair{Any,Any}(2, "2"),Pair{Any,Any}(3, "3"),Pair{Any,Any}(5, "5"),Pair{Any,Any}(8, "8"),Pair{Any,Any}(6, "6"),Pair{Any,Any}(1, "1"))), Any[], Any[], true, "horizontal")

In [ ]:
# Exercise: Create Tetris Pieces, have them fall from the top